include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated/**
    - forms/lib/l10n/**
    - drivers/lib/l10n/**
    - lib/**.g.dart
    - localization/lib/generated/**
    - drivers/**.mocks.dart

linter:
  rules:
 
