name: task_me_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  fl_chart: ^0.55.0
  intl: ^0.17.0
  flutter_svg: ^1.1.1+1
  flutter_colorpicker: ^1.0.3
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  provider: ^6.0.3
  dio: ^4.0.6
  shared_preferences: ^2.0.6
  google_fonts: ^3.0.1
  top_snackbar_flutter: ^2.1.1
  go_router: ^5.1.10
  dynamic_theme:
    git: https://github.com/Norbert515/dynamic_theme.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: ^2.0.0

flutter:
  uses-material-design: true