name: task_me_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # repositories
  dio: 4.0.6
  shared_preferences: 2.0.6

  # models
  json_annotation: any
  freezed_annotation: any

  # state manager
  flutter_bloc: 8.1.1
  bloc: 8.1.0
  provider: 6.0.3

  # ui
  syncfusion_flutter_charts: 22.2.10
  flutter_heatmap_calendar: 1.0.5
  top_snackbar_flutter: 2.1.1
  flutter_quill: 7.4.3
  intl: 0.18.0
  flutter_svg: 2.0.7
  flutter_colorpicker: 1.0.3
  go_router: 5.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: any
  build_runner: any
  freezed: any

  hive_generator: 2.0.0

  flutter_lints: 2.0.0
  lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/screen/
    - assets/animations/